name: Build OpenShift Extension for Docker Desktop

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-extension:
    name: Compile and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Set up Node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'yarn'
          cache-dependency-path: ./client/yarn.lock

      - name: Install dependencies
        run: yarn --cwd ./client

      # Build extension
      - name: Run build
        run: yarn --cwd ./client build

      # Run tests
      - name: Run Tests
        uses: GabrielBB/xvfb-action@fe2609f8182a9ed5aee7d53ff3ed04098a904df2 #v1.0
        with:
          run: yarn --cwd ./client test

  publish-extension:
    name: Build and push image to DockerHub
    needs: build-extension
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        env:
          TAG: 0.0.1-${{github.run_number}}

        run: make push-extension
